#!/usr/bin/env bash
# inspired by https://gist.github.com/noln/8ba9632775c63685e83c3534cbd83079

set -e

usage() {
  echo "usage: compress INPUT OUTPUT [MODE = l,m,s,t]"
  exit 1
}

if [ $# -lt 2 ]; then
  usage
fi

input="$1"
output="$2"
mode="$3"

if [ -f "$output" ]; then
  echo "output already exists: $output"
  usage
fi

case "$mode" in
l) # 2.7k / 2704p
  ffmpeg -i "$input" -vf scale=2704:1520 -c:v libx265 -crf 28 -preset fast "$output"
  ;;

m) # 1440p
  ffmpeg -i "$input" -vf scale=1920:1440 -c:v libx265 -crf 28 -preset fast "$output"
  ;;

s | '') # 1080p (default)
  ffmpeg -i "$input" -vf scale=1920:1080 -c:v libx265 -crf 28 -preset fast "$output"
  ;;

t) # 720p
  ffmpeg -i "$input" -vf scale=1280:720 -c:v libx265 -crf 28 -preset fast "$output"
  ;;

*)
  echo "invalid mode: $mode"
  usage
  ;;
esac
