#!/usr/bin/env bash
# inspired by https://www.imakewebsites.ca/posts/2018/02/17/stabilizing-gopro-video-with-ffmpeg-and-vid.stab/

set -e

usage() {
  echo "usage: gopro-stabalize INPUT OUTPUT"
  exit 1
}

if [ $# -lt 2 ]; then
  usage
fi

input="$1"
output="$2"

if [ -f "$output" ]; then
  echo "output already exists: $output"
  usage
fi

tmp="$(mktemp -d)"
ffmpeg -i "$input" -vf "vidstabdetect=stepsize=16:shakiness=10:accuracy=15:result=$tmp/vectors.trf" -f null -
# ffmpeg -i "$input" -vf "vidstabdetect=stepsize=32:shakiness=10:accuracy=15:show=1" show.mp4
# ffmpeg -i "$input" -y -vf "vidstabtransform=input=$tmp/vectors.trf" -vcodec libx264 -tune film -acodec copy "$output"
ffmpeg -i "$input" -y -vf "vidstabtransform=input=$tmp/vectors.trf:smoothing=15,unsharp=5:5:0.8:3:3:0.4" -vcodec libx264 -tune film -acodec copy "$output"
